---
name: package with latest pg_duckdb release built

env:
  upstream_repo_owner: duckdb
  upstream_repo_repo: pg_duckdb

on:
  workflow_dispatch:
  # disable for now
  #schedule:
  #- cron: '56 0 * * *' # daily

jobs:
  info:
    name: Get info on latest upstream and built package (i.e. v0.3.1)
    runs-on: ubuntu-latest
    outputs:
      upstream_version: ${{ steps.get_latest_package.outputs.result }}
    steps:
    - name: Get latest package release
      id: get_latest_package
      uses: actions/github-script@v6
      with:
        retries: 3
        result-encoding: string
        script: |
          return github.paginate(github.rest.repos.listTags, {
            owner: "${{ env.upstream_repo_owner }}",
            repo: "${{ env.upstream_repo_repo }}"
          }).then(a => a[0].name);
  build:
    name: build new packages
    needs: [info]
    #if: ${{ ! contains(needs.image_tags.outputs.packages, needs.info.outputs.upstream_version) }}
    strategy:
      matrix:
        postgres: ["16", "17"]
        box:
          - { runner: ubuntu-latest, arch: amd64 }
          #- { runner: arm-runner, arch: arm64 }

    runs-on: ${{ matrix.box.runner }}
    container:
      image: ghcr.io/${{ github.repository_owner }}/builder:${{ matrix.postgres }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ env.upstream_repo_owner }}/${{ env.upstream_repo_repo }}
        ref: ${{ needs.info.outputs.upstream_version }}
        submodules: "true"

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true

    - name: install dependencies
      run: |
        apt-get update
        apt-get install -y \
              build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev \
              libxslt-dev libssl-dev libxml2-utils xsltproc pkg-config libc++-dev \
              libc++abi-dev libglib2.0-dev libtinfo6 cmake libstdc++-12-dev \
              liblz4-dev libcurl4-openssl-dev ninja-build

    - name: make
      run: |
        make -j2
        
    - name: make install
      run: |
        make DESTDIR=$PWD/destdir install

    - name: create debian packages
      run: |
        set -x
        extension_name="${{ env.upstream_repo_repo }}"
        extension_name="${extension_name//_/-}" # s/_/-/g
        extension_version="${{ needs.info.outputs.upstream_version }}"
        deb_version="${extension_version/v/}"
        package_dir="$PWD/destdir"

        mkdir -p ${package_dir}/DEBIAN
        cat <<EOF > "${package_dir}/DEBIAN/control"
        Package: $extension_name-pg${{ matrix.postgres}}
        Version: $deb_version
        Section: database
        Priority: optional
        Architecture: ${{ matrix.box.arch }}
        Maintainer: Tobias Florek <me@ibotty.net>
        Description: ${{ env.upstream_repo_owner }} $extension_name PostgreSQL extension
        EOF

        # Create deb package
        chown -R root:root ${package_dir}
        chmod -R 00755 ${package_dir}
        dpkg-deb --build --root-owner-group "$package_dir" "$extension_name-pg${{ matrix.postgres }}.deb"

        mkdir -p deb-uploads
        find . -name *.deb -exec cp {} deb-uploads \;
        echo "found debs:"
        ls $PWD/deb-uploads -la

    - name: update apt repository
      uses: ibotty/apt-repo-update-action@v2
      with:
        debug: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        git_push_branch: apt-repo
        repo_supported_arch: |
          amd64
        repo_supported_distro: |
          bookworm
        private_key: ${{ secrets.APT_KEY }}
        update_directory: ../deb-uploads
